M48
; DRILL file {KiCad (6.0.4-0)} date Friday, 02 September 2022 at 16:24:47
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-02T16:24:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.7835Y-2.6378
X4.7835Y-5.2165
X7.5Y-2.6378
X7.5Y-5.2165
T0
M30
