M48
; DRILL file {KiCad (6.0.4)} date Sat Sep 17 14:54:42 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-17T14:54:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.7835Y-2.6378
X4.7835Y-5.2165
X7.5Y-2.6378
X7.5Y-5.2165
T0
M30
